### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by marijani101** [Tanzania-Developers-Community/made-in-tanzania#2]
Hey there,
do we create pull requests or submit repos that conform to the Contribution guidelines?

**Comment by marijani101** [comment]
> Hey there,
> do we create pull requests or submit repos that conform to the Contribution guidelines?

**Comment by alphaolomi** [comment]
Hello, @marijani101

Please follow the [contributing guide  ](https://github.com/Tanzania-Developers-Community/made-in-tanzania/blob/main/contributing.md) from here.

Improvements will be done to give clear instructions.

**Comment by alphaolomi** [comment]
Hello @marijani101 

We have updated the contribution guide,

both project  #3 and #4 have been added already, in the future we accept contribution via pull requests.


Thank you.
